import type { Metadata } from "next";

import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Alexandria } from "next/font/google"; // جلب خط الإسكندرية العصري
import { SessionProvider } from "next-auth/react";
import { LanguageProvider } from "./Components/LanguageContext";

// const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const alexandria = Alexandria({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="scroll-smooth">
      <body
        className={`${alexandria.className} min-h-screen bg-[#001B2E] antialiased text-white`}
      >
        <SessionProvider>
          <LanguageProvider>{children}</LanguageProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
